
if [ -z "$CUCKOO_DIR" ]
then
    echo "ERROR: Cuckoo directory (variable CUCKOO_DIR) has not been defined"
    exit 1
fi


CUCKOO_ACTION="${CUCKOO_ACTION:=run}"
CUCKOO_OS="${CUCKOO_OS:=linux}"
CUCKOO_ARCH="${CUCKOO_ARCH:=x86_64}"
CUCKOO_DIST_VERSION="${CUCKOO_DIST_VERSION:=debian/8.4}"
if [ -z "$CUCKOO_DIST_VERSION" ]
then
    CUCKOO_ISO_FILE=""
    CUCKOO_DIST_VERSION_DIR=""
else
    CUCKOO_ISO_FILE="${CUCKOO_DIST_VERSION}.iso"
    CUCKOO_DIST_VERSION_DIR="${CUCKOO_DIST_VERSION}/"
fi
CUCKOO_CPU_CORES=${CUCKOO_CPU_CORES:=4}
CUCKOO_CPU_THREADS=${CUCKOO_CPU_THREADS:=2}
CUCKOO_CPU_SOCKETS=${CUCKOO_CPU_SOCKETS:=1}
CUCKOO_TMP_DIR="${TMPDIR:=/tmp}/"
CUCKOO_ISO_DIR="${CUCKOO_DIR}install/iso/${CUCKOO_ARCH}/${CUCKOO_OS}/"


. "${CUCKOO_DIR}lib/env.sh"


QEMU_ARCH="${QEMU_ARCH:=x86_64}"
QEMU_HD_TYPE="${QEMU_HD_TYPE:=virtio}"
QEMU_CDROM_FILE="${QEMU_CDROM_FILE:=}"
QEMU_SMB_DIR="${QEMU_SMB_DIR:=}"
QEMU_NO_USB="${QEMU_NO_USB:=}"
QEMU_FULL_SCREEN="${QEMU_FULL_SCREEN:=}"
QEMU_NO_DAEMONIZE="${QEMU_NO_DAEMONIZE:=}"
QEMU_MEMORY_SIZE="${QEMU_MEMORY_SIZE:=1G}"
case "$QEMU_ARCH" in
    x86_64 )
        QEMU_ARCH_BIN_FILE="$QEMU_ARCH"
        QEMU_CPU_MODEL="qemu64"
    ;;
    x86 )
        QEMU_ARCH_BIN_FILE="i386"
        QEMU_CPU_MODEL="qemu32"
    ;;
esac

QEMU_ARCH_DIR="${CUCKOO_DIR}qemu/${QEMU_ARCH}/"
QEMU_VERSION_FILE="${QEMU_ARCH_DIR}bin/${QEMU_OS}/VERSION"
QEMU_VERSION="$(cat "$QEMU_VERSION_FILE" 2> /dev/null)"
QEMU_BIN_DIR="${QEMU_ARCH_DIR}bin/${QEMU_OS}/${QEMU_VERSION}/"
QEMU_TMP_DIR="${CUCKOO_TMP_DIR}qemu/"
QEMU_HD_DIR="${QEMU_ARCH_DIR}hd/${CUCKOO_OS}/${CUCKOO_DIST_VERSION_DIR}"
QEMU_HD_CLEAN_DIR="${QEMU_ARCH_DIR}hd/${CUCKOO_OS}/clean/"
QEMU_BIN_FILE="bin/qemu-system-${QEMU_ARCH_BIN_FILE}"
